# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default='media/Null.jpg', upload_to='media/'),
        ),
    ]
