# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(blank=True, default='media/Null.jpg', null=True, upload_to='media/'),
        ),
    ]
